package templates

// Field describes a form field for a protocol template.
type Field struct {
	Name        string   `json:"name"`
	Label       string   `json:"label"`
	Type        string   `json:"type"` // string|int|bool|select|password
	Required    bool     `json:"required"`
	Default     any      `json:"default,omitempty"`
	Options     []string `json:"options,omitempty"`
	Description string   `json:"description,omitempty"`
}

// Template is a built-in inbound protocol form schema.
// Secret fields (password, uuid, TLS keys, Reality keys) are NOT exposed here —
// they are auto-generated by inboundfill on create.
type Template struct {
	ID       string  `json:"id"`
	Protocol string  `json:"protocol"`
	Name     string  `json:"name"`
	Fields   []Field `json:"fields"`
}

var builtins = []Template{
	{
		ID:       "inbound.shadowsocks.v1",
		Protocol: "shadowsocks",
		Name:     "Shadowsocks",
		Fields: []Field{
			{Name: "listen", Label: "Listen", Type: "string", Required: false, Default: "0.0.0.0", Description: "Listen address"},
			{Name: "port", Label: "Port", Type: "int", Required: true, Description: "Agent listen port (NAT 外端口在节点「端口映射」配置)"},
			{
				Name:     "method",
				Label:    "Method",
				Type:     "select",
				Required: false,
				Default:  "aes-256-gcm",
				Options: []string{
					"aes-128-gcm",
					"aes-192-gcm",
					"aes-256-gcm",
					"chacha20-ietf-poly1305",
					"xchacha20-ietf-poly1305",
					"2022-blake3-aes-128-gcm",
					"2022-blake3-aes-256-gcm",
					"2022-blake3-chacha20-poly1305",
				},
				Description: "AEAD encryption method (password auto-generated)",
			},
			{
				Name:        "network",
				Label:       "Network",
				Type:        "select",
				Required:    false,
				Default:     "",
				Options:     []string{"", "tcp", "udp"},
				Description: "Empty means both TCP and UDP",
			},
		},
	},
	{
		ID:       "inbound.trojan.v1",
		Protocol: "trojan",
		Name:     "Trojan",
		Fields: []Field{
			{Name: "listen", Label: "Listen", Type: "string", Required: false, Default: "0.0.0.0"},
			{Name: "port", Label: "Port", Type: "int", Required: true},
		},
	},
	{
		ID:       "inbound.vless.v1",
		Protocol: "vless",
		Name:     "VLESS",
		Fields: []Field{
			{Name: "listen", Label: "Listen", Type: "string", Required: false, Default: "0.0.0.0"},
			{Name: "port", Label: "Port", Type: "int", Required: true},
			{Name: "flow", Label: "Flow", Type: "string", Required: false, Description: "Optional, e.g. xtls-rprx-vision"},
			{
				Name:        "tls_mode",
				Label:       "TLS Mode",
				Type:        "select",
				Required:    false,
				Default:     "reality",
				Options:     []string{"none", "tls", "reality"},
				Description: "Default reality; UUID and keys are auto-generated",
			},
			{Name: "server_name", Label: "Server Name (SNI)", Type: "string", Required: false, Default: "www.microsoft.com"},
			{Name: "handshake_server", Label: "Reality Handshake Server", Type: "string", Required: false, Default: "www.microsoft.com"},
			{Name: "handshake_server_port", Label: "Reality Handshake Port", Type: "int", Required: false, Default: 443},
		},
	},
	{
		ID:       "inbound.hysteria2.v1",
		Protocol: "hysteria2",
		Name:     "Hysteria2",
		Fields: []Field{
			{Name: "listen", Label: "Listen", Type: "string", Required: false, Default: "0.0.0.0"},
			{Name: "port", Label: "Port", Type: "int", Required: true},
			{Name: "up_mbps", Label: "Up Mbps", Type: "int", Required: false},
			{Name: "down_mbps", Label: "Down Mbps", Type: "int", Required: false},
		},
	},
	{
		ID:       "inbound.tuic.v1",
		Protocol: "tuic",
		Name:     "TUIC",
		Fields: []Field{
			{Name: "listen", Label: "Listen", Type: "string", Required: false, Default: "0.0.0.0"},
			{Name: "port", Label: "Port", Type: "int", Required: true},
			{
				Name:        "congestion_control",
				Label:       "Congestion Control",
				Type:        "select",
				Required:    false,
				Default:     "cubic",
				Options:     []string{"cubic", "new_reno", "bbr"},
				Description: "QUIC congestion control (UUID/password/TLS auto-generated)",
			},
			{Name: "server_name", Label: "Server Name (SNI)", Type: "string", Required: false, Description: "Optional TLS SNI for clients"},
		},
	},
	{
		ID:       "inbound.anytls.v1",
		Protocol: "anytls",
		Name:     "AnyTLS",
		Fields: []Field{
			{Name: "listen", Label: "Listen", Type: "string", Required: false, Default: "0.0.0.0"},
			{Name: "port", Label: "Port", Type: "int", Required: true},
			{Name: "server_name", Label: "Server Name (SNI)", Type: "string", Required: false, Description: "Optional TLS SNI for clients"},
		},
	},
	{
		ID:       "inbound.vmess.v1",
		Protocol: "vmess",
		Name:     "VMess",
		Fields: []Field{
			{Name: "listen", Label: "Listen", Type: "string", Required: false, Default: "0.0.0.0"},
			{Name: "port", Label: "Port", Type: "int", Required: true},
			{
				Name:        "alter_id",
				Label:       "Alter ID",
				Type:        "int",
				Required:    false,
				Default:     0,
				Description: "0 = AEAD only (recommended); >0 enables legacy",
			},
			{
				Name:        "tls_mode",
				Label:       "TLS Mode",
				Type:        "select",
				Required:    false,
				Default:     "none",
				Options:     []string{"none", "tls"},
				Description: "UUID auto-generated; TLS material auto-generated when tls",
			},
			{Name: "server_name", Label: "Server Name (SNI)", Type: "string", Required: false},
		},
	},
	{
		ID:       "inbound.http.v1",
		Protocol: "http",
		Name:     "HTTP",
		Fields:   userAuthInboundFields("HTTP CONNECT 代理"),
	},
	{
		ID:       "inbound.socks5.v1",
		Protocol: "socks5",
		Name:     "SOCKS5",
		Fields:   userAuthInboundFields("SOCKS5 代理"),
	},
	{
		ID:       "inbound.auto.v1",
		Protocol: "auto",
		Name:     "Auto (HTTP/SOCKS5)",
		Fields:   userAuthInboundFields("同一端口自动识别 HTTP 与 SOCKS5"),
	},
}

func userAuthInboundFields(description string) []Field {
	return []Field{
		{Name: "listen", Label: "Listen", Type: "string", Required: false, Default: "0.0.0.0"},
		{Name: "port", Label: "Port", Type: "int", Required: true},
		{
			Name:        "auth_mode",
			Label:       "Auth",
			Type:        "select",
			Required:    false,
			Default:     "password",
			Options:     []string{"password", "none"},
			Description: description + "；password 模式自动生成用户名和密码",
		},
	}
}

// List returns all built-in protocol templates.
func List() []Template {
	out := make([]Template, len(builtins))
	copy(out, builtins)
	return out
}

// Get returns the template for a protocol id (e.g. "shadowsocks").
func Get(protocol string) (Template, bool) {
	for _, t := range builtins {
		if t.Protocol == protocol {
			return t, true
		}
	}
	return Template{}, false
}
